[package]

name = "flate2"
authors = ["Alex Crichton <alex@alexcrichton.com>"]
version = "0.1.4"
license = "MIT/Apache-2.0"
readme = "README.md"
keywords = ["gzip", "flate", "zlib", "encoding"]
repository = "https://github.com/alexcrichton/flate2-rs"
homepage = "https://github.com/alexcrichton/flate2-rs"
documentation = "http://alexcrichton.com/flate2-rs"
description = """
Bindings to miniz.c for DEFLATE compression and decompression exposed as
Reader/Writer streams. Contains bindings for zlib, deflate, and gzip-based
streams.
"""

[dependencies.miniz-sys]
path = "miniz-sys"
version = "0.1.0"
