parameters:
  os: 'Linux'
  toolchain: 'stable'
  vmImage: 'ubuntu-16.04'

jobs:
- job: ${{ format('{0}_{1}', parameters.os, parameters.toolchain) }}
  pool:
    vmImage: ${{ parameters.vmImage }}
  steps:
    - template: azure-install-rust.yml
      parameters:
        os: ${{ parameters.os }}
        toolchain: ${{ parameters.toolchain }}
    - script: cargo build
    - script: rustdoc --test README.md -L target/debug/deps --extern flate2=target/debug/libflate2.rlib
    - script: cargo test
    - script: cargo test --features zlib
    - script: cargo test --features tokio
    - script: cargo test --features 'tokio zlib'
    - script: cargo test --features zlib --no-default-features
